spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouses_management
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: management
    open-in-view: false

server:
  port: 8087